/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PodcastRecommendationsRouteImport } from './routes/podcast-recommendations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogPostsPostIdRouteImport } from './routes/blog/posts/$postId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRecommendationsRoute = PodcastRecommendationsRouteImport.update({
  id: '/podcast-recommendations',
  path: '/podcast-recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostsPostIdRoute = BlogPostsPostIdRouteImport.update({
  id: '/blog/posts/$postId',
  path: '/blog/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/podcast-recommendations': typeof PodcastRecommendationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/posts/$postId': typeof BlogPostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/podcast-recommendations': typeof PodcastRecommendationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog': typeof BlogIndexRoute
  '/blog/posts/$postId': typeof BlogPostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/podcast-recommendations': typeof PodcastRecommendationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/posts/$postId': typeof BlogPostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/podcast-recommendations'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/'
    | '/blog/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/podcast-recommendations'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog'
    | '/blog/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/podcast-recommendations'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/'
    | '/blog/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PodcastRecommendationsRoute: typeof PodcastRecommendationsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogPostsPostIdRoute: typeof BlogPostsPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast-recommendations': {
      id: '/podcast-recommendations'
      path: '/podcast-recommendations'
      fullPath: '/podcast-recommendations'
      preLoaderRoute: typeof PodcastRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/posts/$postId': {
      id: '/blog/posts/$postId'
      path: '/blog/posts/$postId'
      fullPath: '/blog/posts/$postId'
      preLoaderRoute: typeof BlogPostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PodcastRecommendationsRoute: PodcastRecommendationsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogPostsPostIdRoute: BlogPostsPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
