/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PodcastRecommendationsRouteImport } from './routes/podcast-recommendations'
import { Route as FaviconDoticoRouteImport } from './routes/favicon[.]ico'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRecommendationsRoute = PodcastRecommendationsRouteImport.update({
  id: '/podcast-recommendations',
  path: '/podcast-recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDoticoRoute = FaviconDoticoRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/podcast-recommendations': typeof PodcastRecommendationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/podcast-recommendations': typeof PodcastRecommendationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/podcast-recommendations': typeof PodcastRecommendationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favicon.ico'
    | '/podcast-recommendations'
    | '/robots.txt'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favicon.ico'
    | '/podcast-recommendations'
    | '/robots.txt'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/favicon.ico'
    | '/podcast-recommendations'
    | '/robots.txt'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaviconDoticoRoute: typeof FaviconDoticoRoute
  PodcastRecommendationsRoute: typeof PodcastRecommendationsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast-recommendations': {
      id: '/podcast-recommendations'
      path: '/podcast-recommendations'
      fullPath: '/podcast-recommendations'
      preLoaderRoute: typeof PodcastRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaviconDoticoRoute: FaviconDoticoRoute,
  PodcastRecommendationsRoute: PodcastRecommendationsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
